### ISSUE TITLE
Whole page design

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js.ipfs.io#1]
@akrych we need the page wireframes, design and assets to be able to implement it. Can you add the design to a project in Zeplin/Invision and share here the assets for it?

**Comment by diasdavid** [comment]
Meanwhile, I leave here a preview (what I have access to right now)

![image](https://user-images.githubusercontent.com/1211152/39698413-0321111c-51f5-11e8-9974-412159093b1b.png)

**Comment by akrych** [comment]
@diasdavid It's on Zeplin here: https://zpl.io/VOBLnGP 

I was waiting for your feedback, but If everyting is ok - I will add tomorrow two more illustrations for "Real time applications" and "Explore Blockchains Data" :) 👍

**Comment by akrych** [comment]
> There’s four things that need to be added into the designs:
- Number of contributors after the “Open Source” on the menu
- Add a language selection dropdown to be able to select the site language
- Add a “Alpha” & “Not audited” banner, similar to peerpad
- Ability to showcase demos in the “What can you build” section

Update design with this ^^ 4 things, on Zeplin 👍

**Comment by akrych** [comment]
Add missing illustrations: 

<img width="718" alt="screenshot at may 08 17-39-19" src="https://user-images.githubusercontent.com/22168118/39767443-154061de-52e7-11e8-88ca-2e83d0a52438.png">

<img width="718" alt="screenshot at may 08 17-39-48" src="https://user-images.githubusercontent.com/22168118/39767448-18568c18-52e7-11e8-87aa-1e45f6c26054.png">

<img width="718" alt="screenshot at may 08 17-40-18" src="https://user-images.githubusercontent.com/22168118/39767452-1a3a4506-52e7-11e8-865c-0f39ea480ac7.png">

**Comment by hacdias** [comment]
@akrych those are **really** beautiful!

**Comment by akrych** [comment]
I add also mobile version to the Zeplin 👍 zpl.io/adMeQBl

**Comment by andreforsousa** [comment]
Hello @PedroMiguelSS, @diasdavid, I've already revised the Hero banner considering latest feedback.



![js-ipfs_hero-banner_a_1-1](https://user-images.githubusercontent.com/39052705/42956050-d790d044-8b76-11e8-9a74-7c00977d704a.jpg)
