### ISSUE TITLE
bug seen with js vars in the "Getting Started" part

### ISSUE THREAD

**Issue by jbenet** [ipfs/js.ipfs.io#108]
hey looks like i got the "using the cli" and "using the http gateway" to load their variables from the `const data` in "adding data to ipfs". maybe variable confusion?

![image](https://user-images.githubusercontent.com/138401/43447232-e6a2f516-945f-11e8-83aa-6c50f6671f6d.png)

**Comment by satazor** [comment]
Yep, I guess there's a typo. This is similar to #98. @hugomrdias Will take of fixing this today.
