### ISSUE TITLE
Add .svg mimetype support to ipfs-http-response

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js.ipfs.io#126]

**Comment by satazor** [comment]
Made PR to js-ipfs: 
https://github.com/ipfs/js-ipfs/pull/1482

Will do the same for that module as well.

**Comment by satazor** [comment]
PR to ipfs-http-response: https://github.com/ipfs/js-ipfs-http-response/pull/5/

**Comment by satazor** [comment]
Done in https://github.com/ipfs/js.ipfs.io/pull/134
