### ISSUE TITLE
Since activating service worker, page always scroll down to "service worker gateway" section

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js.ipfs.io#130]
Since I activated the service worker via js.ipfs.io, whenever I visit js.ipfs.io it jumps down to that section.

I could understand it the first time, as it makes sure the little box on the right is visible after activating the gateway, but on the next loads, I don't think it should scroll down there directly.

Using Arch Linux + Firefox 61.0.1 (64-bit)

**Comment by satazor** [comment]
@PedroMiguelSS could you check this out?
