### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs/js.ipfs.io#138]
```json
"incompatibleMessageText": "This browser does not support Service Workers.",
"activatedToggleText": "Disable Service Worker"
```

### `serviceWorker`
- [ ] `incompatibleMessageText`
- [ ] `activatedToggleText`

### `serviceWorker`
- [ ] `incompatibleMessageText`
- [ ] `activatedToggleText`

### `serviceWorker`
- [ ] `incompatibleMessageText`
- [ ] `activatedToggleText`

### `serviceWorker`
- [ ] `incompatibleMessageText`
- [ ] `activatedToggleText`

**Comment by lidel** [comment]
Please check https://github.com/ipfs/js.ipfs.io/pull/168, it removes the need for manual synchronization across locale files.

All you need to do after that PR is merged is to
1. Upload new source strings from `intl/messages/en.json`  via `tx push -s`
2. Download new translation files via `tx pull -a`
3. Commit changes.

**Comment by PedroMiguelSS** [comment]
This issue will be closed as this project was added to Transifex and there is no need of manual synchronization anymore (see #168).
