### ISSUE TITLE
package-lock missmatch causes service-worker error

### ISSUE THREAD

**Issue by satazor** [ipfs/js.ipfs.io#144]
I have `node@10` and `npm@6` but CI has `node@8` and `npm@5.6`. The issue is that whenever I commit a package-lock file made by `npm@6` and the project builds on the CI, the service-worker stops working with a error related with `webcrypto-shim`.

We should try to use `node@10` and `npm@6` in Jenkins to avoid having this issue, see: https://github.com/ipfs/jenkins-libs/#example-2

//cc @VictorBjelkholm

**Comment by VictorBjelkholm** [comment]
The current versions available in jenkins are listed here: https://github.com/ipfs/jenkins/blob/master/update-nodejs-versions.js#L38-L40

Did you try specifying one of them in ci/Jenkinsfile?

**Comment by PedroMiguelSS** [comment]
How do I specify the node version using [website()](https://github.com/ipfs/jenkins-libs/#website-preview-and-deployment-hugo-only)?
Should it be done on the [makefile](https://github.com/ipfs/js.ipfs.io/blob/master/Makefile)?
If so, which node version manager do you use?

//cc: @victorb

**Comment by victorb** [comment]
Is it enough by specifying the npm version? In that case, take a look at the Makefile in PeerPad https://github.com/ipfs-shipyard/peer-pad/blob/master/Makefile

**Comment by PedroMiguelSS** [comment]
Yes, @victorb, it was enough. Thanks.
But shouldn't `nodejs_versions` option be supported on [`website()`](https://github.com/ipfs/jenkins-libs/#website-preview-and-deployment-hugo-only) library function as [`javascript()`](https://github.com/ipfs/jenkins-libs/#javascript) does?
