### ISSUE TITLE
Shorten "Add and retrieve files from anywhere in the IPFS Network" text

### ISSUE THREAD

**Issue by satazor** [ipfs/js.ipfs.io#153]
This is a follow up of #96. The text is very large compared to others. @diasdavid can we make it a bit shorter?

**Comment by PedroMiguelSS** [comment]
@diasdavid can you make this text `IPFS is designed to use the power of Content Addressing and Process Addressing to find the nodes in the network that have the content you are looking for and retrieve it. In the same way, you can add any piece of data and other nodes will find it too.` a little bit more concise, please? :D

**Comment by diasdavid** [comment]
Wanna try take a stab at it?

**Comment by PedroMiguelSS** [comment]
Do you like any of these 2 options?

- `IPFS is designed to use the power of Content Addressing to find the nodes in the network that have the content you are looking for. In the same way, you can add data and other nodes will find it too.`
- `IPFS is designed` to use the power of Content Addressing to find the nodes in the network that have the content you want. This way, you can add data and other nodes will find it too.`

**Comment by diasdavid** [comment]
1) 👍🏽
