### ISSUE TITLE
Automate both ipfs add and ipfs pin add commands

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs/js.ipfs.io#171]
Currently, when we want to deploy a new version, the website must be manually added to ipfs through:
```sh
> ipfs add -r public/
> ipfs pin add -r /ipfs/<resulting-hash>
```

And then, the `<resulting-hash>` must be added to each translation file before it gets merged to `production`. 
`serviceWorker` is the object that should be updated. Example:
```
"serviceWorker": {
    ...
        "activationSuccessText": "(...)js.ipfs.io - /ipfs/<resulting-hash>](https://js.ipfs.io/ipfs/<resulting-hash>\n(...)"
    ...
}
```

This process should be automated.

**Comment by PedroMiguelSS** [comment]
Also, we should have the example websites list externalized instead of having them on translations files as stated [here](https://github.com/ipfs/js.ipfs.io/pull/206#issuecomment-439619702).

**Comment by daviddias** [comment]
Is this still a thing?

**Comment by daviddias** [comment]
@PedroMiguelSS you can use DNS resolution from within the website itself to get the latest js.ipfs.io hash without having to do this manually. @lidel, @alanshaw can you share a snippet of JS on how @PedroMiguelSS can use the gateway nodes to do this?

**Comment by lidel** [comment]
Fun fact: regular DNSLink lookup works in web browser, you can read current value via:
```js
ipfs.dns('js.ipfs.io').then(path => console.log(path))
```

Note that:

- We don't have DNS lookup API in browser, but our public gateway does, so js-ipfs running in browser context will fallback to regular HTTP GET for https://ipfs.io/api/v0/dns/js.ipfs.io :ok_hand:
- TTL for js.ipfs is 60 seconds so you may need to wait 1 minute before new value is returned.

**Comment by alanshaw** [comment]
Yep, that snippet looks good to me.

Also worth noting, both [webui](https://github.com/ipfs-shipyard/ipfs-webui) and the [blog](https://github.com/ipfs/blog) use CI to add and pin a successful build. I would look at those projects when trying to automate this deployment.

**Comment by olizilla** [comment]
_is this still a thing_ - it adds friciton to the deploy process, and means we can't auto-deploy on merge like we do the other sites.

**Comment by olizilla** [comment]
See also: #246 

@PedroMiguelSS is this something you plan to fix? Can we get an ETA?

**Comment by PedroMiguelSS** [comment]
You're right, this issue must be addressed. Our sprints on [IDM](https://github.com/ipfs-shipyard/pm-idm) project are 2 weeks long. The current sprint will end on May 6th and I'll include a task on the next sprint for this issue. Is that ETA ok for you?

**Comment by terichadbourne** [comment]
Jumping in with the annual "is this still a thing" nudge after merging to master in January and failing to notice until today that my changes were never published because I failed to do all the steps manually. 🤦‍♀️
