### ISSUE TITLE
Error getting IPFS in Chrome & Firefox

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js.ipfs.io#173]
I saw for the first time today:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/1211152/45722486-742b0b80-bb61-11e8-8341-b86f5bedb03f.png">

This is happening both in Chrome and Firefox.

@PedroMiguelSS can you check this asap?

**Comment by hugomrdias** [comment]
Last ipfs release didn't include dist folder.

https://unpkg.com/ipfs@0.32.1/

/cc @alanshaw

**Comment by alanshaw** [comment]
Please ping me on IRC/Slack if something major like that happens again - I don't always check github notifications so frequently.

**Comment by alanshaw** [comment]
Fixed in 0.32.2.

https://unpkg.com/ipfs@0.32.2/

**Comment by PedroMiguelSS** [comment]
Thanks @alanshaw!
