### ISSUE TITLE
Support embeded apps

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js.ipfs.io#18]
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/1211152/42229990-2108c056-7ee8-11e8-9d96-47c0bc521b88.png">

This section needs to be populated by multiple tiny apps. 

@PedroMiguelSS we went through this in our last check in, is there code to make it possible to create this tiny apps?

**Comment by diasdavid** [comment]
Dropping the priority of this one as it will go only in the next iteration (post DWeb Summit)

**Comment by satazor** [comment]
@diasdavid I will close this in favor of #156
