### ISSUE TITLE
Multiple translations vanished with the last release

### ISSUE THREAD

**Issue by daviddias** [ipfs/js.ipfs.io#187]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/1211152/46491004-2b867a00-c812-11e8-810d-f25f209a267f.png">

**Comment by diasdavid** [comment]
@PedroMiguelSS can you check this?

**Comment by PedroMiguelSS** [comment]
Translations are now managed by transifex. Only 100% translated languages are pulled. That’s the reason why some of them are missing.

**Comment by diasdavid** [comment]
Check in with the original translators and see if they have extra availability to help us land the translations again.

**Comment by diasdavid** [comment]
Also, it would be good to have a link after the last translation that takes folks to transifex to add their own translation

**Comment by PedroMiguelSS** [comment]
I didn't notify each original translators yet because I was waiting for the final copy (description) of `What you can build` section. I was trying to avoid to ask the original translators many times for new translations.
Can you tell me what do you expect in that section description @diasdavid?
