### ISSUE TITLE
Does not show latest release

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js.ipfs.io#188]
Currently showing 0.32.2 for me but 0.32.3 was published 9 days ago.

**Comment by satazor** [comment]
This is a problem with npms that we are using to fetch the latest version. The reason is that npms is failing to analyze packages because nsp was deprecated (which we use to fetch vulnerabilities). This should be fixed soon.

**Comment by satazor** [comment]
@alanshaw Meanwhile this was solved!

**Comment by alanshaw** [comment]
0.33.0 was released last week but it's showing 0.32.3...

**Comment by satazor** [comment]
I've triggered the analysis manually and it's back to normal. If this happens again, please let me know and I will further investigate it.
