### ISSUE TITLE
Document how stats on the hero section are being fetched.

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs/js.ipfs.io#21]
I was implementing the IPFS package details ("current version", "latest update" and "downloads last month") and I was using [npmstat](https://github.com/bukinoshita/npmstat) package to get the info. However, I was getting a `CORB` ([Cross-Origin Read Blocking](https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md#Determining-whether-a-response-is-CORB_protected)) warning and getting no response. 

After some research, we think that the problem might be caused by the sniffing mechanism of the chrome browser. Chrome seems to be sniffing the response to check its content-type. However, a mismatch seems to happen and the browser gives a warning and resolves the promise with no data.
If the response header had `X-Content-Type-Options` set to `nosniff` the browser would skip this kind of verification and would return the response data as it is. 

To partially solve this issue, I'll use [npms API](https://api-docs.npms.io/) and I'll be able to get both "current version" and "latest update". However, I will no be able to get the number of "downloads of the last month".

Does anyone have any idea on how to bypass this issue?

**Comment by diasdavid** [comment]
This has been fully solved thanks to npms.io, correct? //cc @satazor

**Comment by satazor** [comment]
@diasdavid correct, see https://github.com/ipfs/js.ipfs.io/blob/239bc814e5f710c0483d12ecc86f8987b6159e50/src/shared/components/hero-section/index.js#L33

One downside is that the `npms.io` data for each package is only updated each 15 or whenever a new version of package gets published. If that's not an issue, we can indeed close this.

**Comment by diasdavid** [comment]
It's fine for now. Let's make sure it gets captured on the README though :)

**Comment by satazor** [comment]
Closing in favor of #157
