### ISSUE TITLE
Auto deploy to a staging environment 

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js.ipfs.io#23]
Can we haz this plz? 

![image](https://user-images.githubusercontent.com/1211152/42334011-963f0e12-807c-11e8-8f60-3259433bce3c.png)

**Comment by VictorBjelkholm** [comment]
Documented how to setup here: https://github.com/ipfs/jenkins-libs/#example-with-multiple-branchesrecords

**Comment by diasdavid** [comment]
@VictorBjelkholm thank you for making this.

**Comment by VictorBjelkholm** [comment]
@diasdavid the records have been setup correctly but this still seems to be missing a correct Jenkinsfile to have the staging env correctly updated when master changes.

**Comment by diasdavid** [comment]
@VictorBjelkholm like this https://github.com/ipfs/js.ipfs.io/pull/49 ??

**Comment by VictorBjelkholm** [comment]
Works perfectly now :)
