### ISSUE TITLE
Directory "cypress" not ignored?

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js.ipfs.io#239]
I've run `npm install`, `npm run test:e2e` and `npm run test:e2e:ci` and now I have a `cypress` directory that git reports as new - should it be ignored?

**Comment by PedroMiguelSS** [comment]
Yes, it should be ignored. Cypress tests were made to run on `pre-push` to avoid possible errors on the service worker ([issue here](https://github.com/ipfs/js.ipfs.io/issues/199)). Ideally, the tests should run on the CI. This is just a temporary solution (check [this comment](https://github.com/ipfs/js.ipfs.io/issues/199#issuecomment-448159442)).

**Comment by satazor** [comment]
PR at #240 

Thanks for spotting this @alanshaw. PS: I accidentally closed this issue
