### ISSUE TITLE
The Service Worker Stats page is being captured by gatsby

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js.ipfs.io#24]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/1211152/42425921-4f70b3ce-8323-11e8-9f1a-26d9f71df333.png">

**Comment by vasco-santos** [comment]
I forgot to change the `README.md`, but the stats page scope was changed to `/stats`.

Ref:
https://github.com/ipfs-shipyard/service-worker-gateway/pull/17
https://github.com/ipfs-shipyard/service-worker-gateway/pull/20

**Comment by diasdavid** [comment]
I guess this is blocked on solving #47 now.

**Comment by vasco-santos** [comment]
Using `localhost` should work fine, as well as using an HTTP server with the public folder that results from the build. 

The #47 problem is when using the version running on `dev.js.ipfs.io` only.

**Comment by diasdavid** [comment]
@vasco-santos is the Service Worker on _this page_ working 100% right now?

**Comment by vasco-santos** [comment]
I cloned the repo, installed everything from scratch, removed my brower's cache, and it seems to be working 100% locally.

![image](https://user-images.githubusercontent.com/7295071/43138823-086ab11a-8f48-11e8-9f00-dd785ee83fa9.png)

**Comment by vasco-santos** [comment]
I also tested in `firefox` now and it is working

**Comment by diasdavid** [comment]
This seems fixed now, still some UX improvs to be made, let's follow the rest on #30
