### ISSUE TITLE
Possible typo: libp2p / ipfs

### ISSUE THREAD

**Issue by mishmosh** [ipfs/js.ipfs.io#252]
The Community section of the website footer refers to libp2p twice, in line 164 of /messages/en.json.

* "code implementations and tools using **libp2p**"
* "join our regular product calls to discuss **libp2p** with us."

Is this supposed to say ipfs? I can make a PR if so.

**Comment by satazor** [comment]
//cc @daviddias

**Comment by daviddias** [comment]
great catch @mishmosh. Yes please submit the PR :) Thank you!

**Comment by alanshaw** [comment]
reoslved in https://github.com/ipfs/js.ipfs.io/pull/264
