### ISSUE TITLE
Tutorial Link on js.ipfs.io leads to 404 page

### ISSUE THREAD

**Issue by lindseymysse** [ipfs/js.ipfs.io#285]
Behavior: when I click the link Tutorials on the js.ipfs.io page it leads me to https://github.com/ipfs/js-ipfs/tree/master/examples#js-ipfs-examples-and-tutorials which is a 404 page. 

Expected Behavior: When I click the link Tutorials on the page it should lead me to a page of examples and tutorials. 

Keep being awesome!

**Comment by terichadbourne** [comment]
Thanks for reporting, @lindseymysse. Are you still having this issue? For me the page you've linked to loads correctly.

**Comment by lindseymysse** [comment]
Looks like you fixed it! Thanks a ton.
