### ISSUE TITLE
Animation is very CPU hungry

### ISSUE THREAD

**Issue by lgierth** [ipfs/js.ipfs.io#29]
The circling dots animation eats about 200% CPU on my laptop. Makes me close the website right away :(

**Comment by PedroMiguelSS** [comment]
You're right @lgierth, I didn't notice that. I was researching trying to find out a reason for this CPU consumption and then I realized that applying linear transformations to SVG elements does trigger re-layout and re-painting. I'll fix this as soon as possible.

**Comment by lgierth** [comment]
This still eats a lot of CPU, in both Chromium 67 and Firefox 62b12 on Linux. In FF on my laptop the page is barely usable, maybe 1 or 2 FPS. Chromium is more responsive, but still eats a whole core.

**Comment by satazor** [comment]
@lgierth I'm not experiencing this issue, it's very smooth on my Macbook Pro both in Chrome and FF. 

What are your laptop secs? Do you have the Linux drivers for your card? Perhaps we could disable the animation for lower end hardware if that's the case?

**Comment by lgierth** [comment]
What's your CPU utilization while having the page open? :) Things can look smooth and still eat multiple CPU cores (and thus battery). I recommend a systray statistics tool, in ubuntu I'm using [indicator-multiload](https://lh4.googleusercontent.com/-JnxG3ZNRNcE/Tez0k030V8I/AAAAAAAAEzM/8-qPnGaW6Do/s2000/indicator-multiload.png), there's definitely similar tools for OSX. The advantage is that you *always* have a sense of system load just with a glance to the systray.

- Desktop: 8-core i7-7700T, Intel HD Graphics 630
  - In FF the animation and page scroll are laggy
- Laptop: 4-core Pentium N4200, Intel HD Graphics 505
  - In FF the animation and page scroll are maybe 2 FPS (didn't measure, but that's what it feels like)

Is there more info I can provide? Maybe more runtime profiles?

Please make sure to occasionally test your work on hardware that is not a Macbook Pro -- we can't expect people to have high-end hardware just to open our website. Both my desktop and laptop are passively cooled, but I imagine many computers will spin up their fans right away :)

**Comment by lgierth** [comment]
It does look gorgeous though :sunglasses:

**Comment by satazor** [comment]
My laptop is specs are: i7 4 cores, Intel Iris Plus Graphics 650

I guess my graphics card is a little bit better. Here's the CPU amount being used:

<img width="441" alt="screen shot 2018-07-30 at 00 55 21" src="https://user-images.githubusercontent.com/1017236/43371966-4fcb9d90-9393-11e8-9ea5-d3542a9e144a.png">

(Chrome task manager)

It's taking ~10% of the CPU which is fair enough. It's also doing work on the GPU.

Your both PCs are on Linux right? A possible cause is that Chrome / FF is not taking advantage of your CPU for some reason. Could you take a screenshot of the Task Manager like mine?

**Comment by satazor** [comment]
I've made a lot of mistakes in my last comment, edited.

**Comment by lgierth** [comment]
On the laptop:
- Browser 16% CPU
- GPU Process 37 - 41% CPU
- Tab: JS IPFS 16 - 90% CPU (but mostly below 40%)

On the desktop:
- Browser 14 - 22% CPU
- GPU Process 25 - 33% CPU
- Tab: JS IPFS 16 - 90% CPU (but mostly below 60%)

**Comment by lgierth** [comment]
And add to that ~25% CPU constantly used by compiz (compositor), and you end up with a strong blue CPU usage graph in my systray :):)

**Comment by satazor** [comment]
Here's a few different things to consider. Note that they aren't mutually exclusive:

- Disable the animation on low-end devices by using a library that measures the machine performance; if it's costly to do this evaluation, cache it in local storage
- Animation is paused until page loads or `requestIdleCallback` is called (which one works best). Note that  `requestIdleCallback` is not available in all browsers, we need to polyfill it. This will prevent the "choppiness" while the page is still loading
- Try to solve the SVG being cut off/weird looking in Firefox; it seems that the parts that are offscreen are being "optimized" and they aren't rendered correctly when entering the screen. Perhaps we could trick the browser with `margin-top` and `translate`?
