### ISSUE TITLE
Service Worker Gateway Section

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js.ipfs.io#30]
Plan: 

- 1. Draw a low fidelity sketch of the Service Worker Gateway Animation - @diasdavid
- 2. Ask @akrych to save us all by making it beautiful and functional
- 3. Get @PedroMiguelSS and @hugomrdias to implement it.

**Comment by diasdavid** [comment]
@PedroMiguelSS can we get the animation as is on the Website asap so that we get a sense for the whole flow?

**Comment by diasdavid** [comment]
<img width="967" alt="image" src="https://user-images.githubusercontent.com/1211152/43338039-a28a3df8-91d5-11e8-8e17-285d3c8ea86b.png">

**Comment by satazor** [comment]
@diasdavid As we discussed in Slack, it's not possible to have the service worker when serving from `/ipfs/xxx` or `/ipns/xxx`. The reasoning is that the service worker must be at the root to intercept all the network calls.

There are a few solutions but they involve setting HTTP headers, like `Service-Worker-Allowed`. More info on https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers.

For now, I will show a warning in such cases.

**Comment by diasdavid** [comment]
This text box still needs to be stylized 

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/1211152/43356425-dbc3aeba-9270-11e8-9533-0b3b0e8b3252.png">

**Comment by satazor** [comment]
@vasco-santos is there any design for this?

**Comment by vasco-santos** [comment]
@satazor There are some guidelines for that design. @andreforsousa provided them to @PedroMiguelSS . I don't know if he already started implementing it.

**Comment by satazor** [comment]
@PedroMiguelSS can you give us an update on this?

**Comment by PedroMiguelSS** [comment]
@andreforsousa did not have time to design it. I styled it just a bit so that is not so raw.
Here's a preview of what is implemented right now:
<img width="1440" alt="screen shot 2018-07-30 at 03 30 05" src="https://user-images.githubusercontent.com/11461281/43374754-353f9c7c-93a9-11e8-8534-9c9c871bf81f.png">

**Comment by satazor** [comment]
It's not beautiful but it's okay. I guess you may ask @andreforsousa for advice tomorrow morning?

**Comment by andreforsousa** [comment]
There's a typo on the first description:

> "would _normally_ do"


Here's the current proposal for mobile and desktop version, specs already prepared with the html files and also the "close.svg" icon. @PedroMiguelSS, here's the link: [Specs folder](https://drive.google.com/drive/folders/1mCH47-6xtxVtG88eqnKGxBvpU-3yRjxL?usp=sharing)


Thank you.

![page-1-service-worker-illustration_a2-2-desktop](https://user-images.githubusercontent.com/39052705/43404148-b948a288-940e-11e8-9a91-edf36cbcd267.png)

![page-1-service-worker-illustration_a2-2-mobile](https://user-images.githubusercontent.com/39052705/43404154-bbd4c748-940e-11e8-9543-9458234baa84.png)

**Comment by diasdavid** [comment]
When activated, it show a different message
<img width="486" alt="image" src="https://user-images.githubusercontent.com/1211152/43496459-50d1ecde-94f2-11e8-8890-f3872e278c35.png">

**Comment by PedroMiguelSS** [comment]
Did you mean that it should show a different message when is activate? @diasdavid

**Comment by diasdavid** [comment]
@PedroMiguelSS exactly.

**Comment by diasdavid** [comment]
<img width="1352" alt="image" src="https://user-images.githubusercontent.com/1211152/43962386-408cd908-9cc0-11e8-9eb7-b5f5748a5d4d.png">

**Comment by PedroMiguelSS** [comment]
The master branch already has the latest hash. Though, I will update to the latest hash as soon as we deploy the latest fixes and close this issue.

**Comment by satazor** [comment]
Hash was updated.
