### ISSUE TITLE
ipfs.cat example on website not working correctly

### ISSUE THREAD

**Issue by mxk1011** [ipfs/js.ipfs.io#301]
- **Version**:
commit: "55cb49900"
golang: "go1.15.15"
ipfs-http-client: "1.0.0"
repo: "11"
system: "amd64/linux"

- **Platform**:
Chromium Version 93.0.4573.0

- **Subsystem**:

#### Severity:
High

#### Description:
I copied the example from the website to retrieve content from IPFS in browser via JS

#### Steps to reproduce the error:
```const client = await create('https://ipfs.infura.io:5001/api/v0');
const stream = client.cat(
            'QmPChd2hVbrJ6bfo3WBcTW4iZnpHm8TEzWkLHmLpXhF68A',
);
let data = '';

for await (const chunk of stream) {
   // chunks of data are returned as a Buffer, convert it back to a string
   data += chunk.toString();
}
console.log(data);
```

this code snippet using "ipfs-http-client": "^53.0.1" will not print a string as shown on the website. It returns an array of ints:
72,101,108,108,111,44,32,60,89,79,85,82,32,78,65,77,69,32,72,69,82,69,62 

Also I did not find any solution yet to simply return a string value of the content from IPFS. Can somebody please check this?

**Comment by lidel** [comment]
The example on https://js.ipfs.io/ needs updating. PRs welcome :pray:
