### ISSUE TITLE
Service Worker is failing to load

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js.ipfs.io#39]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/1211152/42950228-6f255562-8b6b-11e8-8e5d-dd29425c5993.png">

**Comment by vasco-santos** [comment]
I [updated](https://github.com/ipfs-shipyard/service-worker-gateway/pull/19) the `ipfs` dependency in the `service-worker-gateway` and now I am facing another problem regarding the `Big.js` dependency, the same as was solved in [here](https://github.com/ipfs/js-ipfs/pull/1364/files). But, as this project is using Webpack 1 ( 😢), I have to go with a different solution.

**Comment by diasdavid** [comment]
Why can't this project use the latest WebPack?

**Comment by vasco-santos** [comment]
As far as I know, Gatsby is only compatible with Webpack v1, but @satazor or @PedroMiguelSS can confirm this since they bootstrapped the project.

**Comment by satazor** [comment]
Current stable version of Gatsby still uses webpack 1 unfortunately. They will be releasing a new major with webpack 4 soon.

**Comment by diasdavid** [comment]
@vasco-santos, you can always use the bundled version of js-ipfs so that webpack doesn't need to touch it here for the Service Worker.

**Comment by satazor** [comment]
Fix in #43
