### ISSUE TITLE
Markdown support

### ISSUE THREAD

**Issue by PedroMiguelSS** [ipfs/js.ipfs.io#46]
@diasdavid, I saw that you are using markdown on features description. I didn't know we should be supporting that. I've found a library ([react-markdown](https://github.com/rexxars/react-markdown)) that handles it very well. Can you please tell me in which sections we should support markdown?

**Comment by diasdavid** [comment]
It's useful to be able to addr urls to the description of some sections. Markdown or html, both work for me.
