### ISSUE TITLE
dependency not found when hosted fails service worker installation

### ISSUE THREAD

**Issue by vasco-santos** [ipfs/js.ipfs.io#47]
When this website is built locally, and then exposed locally with the `http-server`, the build seems fine. However, when visiting the website through https://dev.js.ipfs.io and enabling the service worker, its installation fails due to a dependency not being found.

`Error: Cannot find module "webrtcsupport"`

After analysing the `sw.map`, this dependency should be found at `"webpack:///./~/webrtcsupport/index-browser.js"`. Using the `sources` tab of the chrome developer tools, the file cannot be found in that directory. On the other side, when running this build locally, the dependency is found at `"webpack:///./~/webrtcsupport/index-browser.js"`

<img width="1081" alt="dev" src="https://user-images.githubusercontent.com/7295071/43067401-2f67c4e0-8e5f-11e8-9c13-81536e44b481.png">
<img width="1041" alt="local" src="https://user-images.githubusercontent.com/7295071/43067403-2f894d04-8e5f-11e8-8c13-17d35575df72.png">

**Comment by vasco-santos** [comment]
cc @hugomrdias

**Comment by diasdavid** [comment]
@vasco-santos @hugomrdias is this related with the WebPack 1 issues?

Why not use the `dist` version of js-ipfs??

**Comment by hugomrdias** [comment]
our current dist bundle doesn't support es5 uglifyjs

**Comment by diasdavid** [comment]
Can this be considered "fixed" ? @hugomrdias

**Comment by diasdavid** [comment]
This has been fixed 🚀
