### ISSUE TITLE
Use standardjs

### ISSUE THREAD

**Issue by satazor** [ipfs/js.ipfs.io#5]
At the moment, we are using `eslint` with a custom config.

As per the [community guidelines](https://github.com/ipfs/community), we should be using StandardJS.

**Comment by VictorBjelkholm** [comment]
Fun fact, we're kind of using StandardJS but not really, which means we're not using StandardJS at all.

In the end, our config is here: https://github.com/ipfs/eslint-config-aegir which is based on StandardJS but with "Enforce the use of strict mode" as a additional rule. Easiest to use it, is to include aegir in the project (which probably is a good idea anyways, comes with testing/building and bunch of other goodies) and use the `aegir lint` command.

**Comment by diasdavid** [comment]
We are compatible with StandardJS, just so happens that we found useful to add extra rules for our lint config in our modules.

**Comment by diasdavid** [comment]
Done with #19
