### ISSUE TITLE
Must use relative links on websites

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/js.ipfs.io#51]
Loading the website via https://dev.js.ipfs.io/ and everything works fine. But if you resolve it to `/ipfs/QmZdddeppG8x16QxyuBW4zeNLVAUuBmDj7NVUcLkYkmCJC` and then try to load https://ipfs.io/ipfs/QmZdddeppG8x16QxyuBW4zeNLVAUuBmDj7NVUcLkYkmCJC/ you'll see that the image does not load properly. This is because the link is not relative but absolute, leading the image to be loaded from https://ipfs.io/static/cube.9eaf9eeb.png rather than https://ipfs.io/ipfs/QmZdddeppG8x16QxyuBW4zeNLVAUuBmDj7NVUcLkYkmCJC/static/cube.9eaf9eeb.png

**Comment by vasco-santos** [comment]
@hugomrdias is currently tackling this problem

**Comment by diasdavid** [comment]
Two sections still broken:

<img width="1666" alt="image" src="https://user-images.githubusercontent.com/1211152/43316263-0b117fae-9199-11e8-8186-fbe81b42807b.png">

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/1211152/43316270-117c2678-9199-11e8-9750-d1b5ef4ec7dd.png">

Note, this is P1, not P0
