### ISSUE TITLE
Fix contributors section - Needs Hex Grid

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js.ipfs.io#52]
<img width="1578" alt="image" src="https://user-images.githubusercontent.com/1211152/43136393-e1617e36-8f48-11e8-8787-bd59942285b0.png">

**Comment by PedroMiguelSS** [comment]
It already has the hex grid implemented. 
The `iframe` that embed the grid is commented. But we need to host the website that contains the grid to use it on the `iframe`. Similar to what was done on [protocol.ai](https://protocol.ai/team/).

<img width="708" alt="screen shot 2018-07-24 at 13 57 42" src="https://user-images.githubusercontent.com/11461281/43139482-bcfc78e2-8f49-11e8-92ea-20123b38483f.png">

**Comment by diasdavid** [comment]
@PedroMiguelSS add it to IPFS and post the hash here, we can pin it

**Comment by PedroMiguelSS** [comment]
Here is the hash: `QmNZBjJxrqVE6VXmxHzkS9oqguYZC5NhzQxD7G8B7zSeJ5`

**Comment by diasdavid** [comment]
@PedroMiguelSS that hash was pinned, anything left other than adding to the page?

**Comment by PedroMiguelSS** [comment]
My next PR #54 already adds the hex grid to the page and it will close this issue.

**Comment by diasdavid** [comment]
One last thing to fix in this section:

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/1211152/43289851-86ed9f9e-912c-11e8-89eb-081cdfa69548.png">

**Comment by satazor** [comment]
I guess we can close this after #76 gets merged.

**Comment by satazor** [comment]
@diasdavid closing this as #76 is merged
