### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by alanshaw** [ipfs/js.ipfs.io#96]
Some of these are opinions, it looks and works great btw, 99% awesome :D The service worker animation is 👌 

* [ ] Circling dots on Firefox are chuggy until the whole page is loaded
* [x] Portuguese translation isn't working for me
* Features
    * [x] Hover effect on the icons gives me a false sense of them being clickable
    * [ ] Body content for "Add and retrieve files from anywhere in the IPFS Network" is much longer than the first 3 items so there's a big white space area that looks a little weird
    * [ ] Left align the body content for easier readability?
    * [x] "libp2p is built in" - add link to libp2p.io?
* What people are building with it
    * [x] Gray logos make them look disabled
    * [x] Left/right navigation click area is too small (only the visible area of the arrow)
* Publications & Talks
    * [x] Left/right navigation click area is too small (only the visible area of the arrow)
* Community
    * [x] Links aren't wired up

🚀 👍

**Comment by diasdavid** [comment]
@alanshaw converted your feedback to check boxes so that we can go through all of them.

**Comment by satazor** [comment]
> Circling dots on Firefox are chuggy until the whole page is loaded

This will be handled in #29.

> Body content for "Add and retrieve files from anywhere in the IPFS Network" is much longer than the first 3 items so there's a big white space area that looks a little weird

Will create a new issue for this.

> Left align the body content for easier readability?

This was indeed a design choice and it would require a lot of sections to be thought out differently.

---

Closing this as other stuff was addressed, @alanshaw thank you for your valuable feedback.
