### ISSUE TITLE
Getting started fails when content fails - non base58 char

### ISSUE THREAD

**Issue by diasdavid** [ipfs/js.ipfs.io#98]
<img width="930" alt="image" src="https://user-images.githubusercontent.com/1211152/43398636-8836ea5c-93bd-11e8-82ab-4d432ab6fcfa.png">

**Comment by hugomrdias** [comment]
Did you add 3 chars to the cid?

**Comment by diasdavid** [comment]
@hugomrdias it seems that there is a problem with the hash passing from one example from the other. If I manually copy the hash from above and paste it here (creating zero visual changes), it works. If I don't, it fails.

**Comment by hugomrdias** [comment]
This is already fixed in master. Thank you for reporting.
